# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Fifish' do
pod 'CocoaAsyncSocket', '~> 7.5.0'
pod 'SDWebImage', '~> 3.8.1'
pod 'GPUImage', '~> 0.1.7'
pod 'pop', '~> 1.0'
pod 'MJRefresh'
pod 'MJExtension'
pod 'Masonry'
pod 'JKDBModel-JDBR', '~> 0.0.1'
pod 'UICollectionViewLeftAlignedLayout'
end
